[package]
org = "ballerina"
name = "test"
version = "0.0.0"

[[platform.java11.dependency]]
path = "../libs/testerina-core-2.0.0-Preview9-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "mock"
version = "0.0.0"


[[platform.java11.dependency]]
path = "../libs/java-diff-utils-4.5.jar"
groupId = "io.github.java-diff-utils"
artifactId = "java-diff-utils"
version = "4.5.0"
