[package]
org = "ballerina"
name = "runtime"
version = "0.5.0"

[[platform.java11.dependency]]
path = "../libs/ballerina-runtime-api-2.0.0-Preview9-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "runtime"
version = "0.5.0"
