[project]
org-name = "ballerina"
version = "0.6.0"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "system"
    version = "0.6.0"
    path = "<PATH>/ballerina-system-<VERSION>.jar"
    groupId = "ballerina"
    modules = ["system"]

    [[platform.libraries]]
    path = "../../../../io/build/libs/ballerina-io-<VERSION>.jar"
