[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "time"
    version = "1.0.0"
    path = "<PATH>/ballerina-time-<VERSION>.jar"
    groupId = "ballerina"
    modules = ["time"]
